# Generated by Django 3.0.7 on 2020-06-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('idTelegram', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreAbogado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('idCaso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCaso', models.CharField(max_length=100)),
                ('archivoCaso', models.CharField(max_length=200)),
                ('numK', models.IntegerField()),
                ('cifrado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAbogados.Casos')),
                ('idTelegram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAbogados.Abogado')),
            ],
        ),
    ]
